# Generated by Django 2.1.4 on 2019-01-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=40)),
                ('minPersonnel', models.IntegerField(default=4)),
                ('maxPersonnel', models.IntegerField(default=8)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reesrvationID', models.AutoField(primary_key=True, serialize=False)),
                ('numOfReserve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('timeTableIdx', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('timezone', models.IntegerField(default=-8)),
                ('isAvailable', models.BooleanField(default=True)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Class')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userEmail', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=40)),
                ('thirdPartySignUp', models.IntegerField(default=1)),
                ('isLecturer', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeTableIdx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TimeTable'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='userEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.AddField(
            model_name='class',
            name='userEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
